# Generated by Django 3.0.4 on 2020-03-12 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exlibris', '0002_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lend',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lends', to='exlibris.Book'),
        ),
        migrations.AlterField(
            model_name='lend',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lends', to='exlibris.Reader'),
        ),
    ]
