# Generated by Django 3.0.4 on 2020-03-13 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exlibris', '0003_auto_20200312_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField(verbose_name='date_birth')),
                ('place_birth', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exlibris.Author')),
            ],
        ),
    ]
