# Generated by Django 3.0.4 on 2020-04-25 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exlibris', '0004_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biography', to='exlibris.Author'),
        ),
    ]
