# Generated by Django 3.0.4 on 2020-05-04 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exlibris', '0005_auto_20200425_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exlibris.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('books', models.ManyToManyField(through='exlibris.Entry', to='exlibris.Book')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exlibris.Rating'),
        ),
    ]
