# Generated by Django 3.0.4 on 2024-02-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exlibris', '0010_auto_20200602_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
